from locust import HttpUser, task, between


class AgentOpsUser(HttpUser):
    wait_time = between(1, 3)

    def on_start(self):
        resp = self.client.post("/api/auth/login", json={
            "email": "admin@agentops.dev",
            "password": "admin123",
        })
        if resp.status_code == 200:
            data = resp.json()
            self.token = data["access_token"]
            self.headers = {"Authorization": f"Bearer {self.token}"}
        else:
            self.token = None
            self.headers = {}

    @task(3)
    def list_incidents(self):
        if self.token:
            self.client.get("/api/incidents", headers=self.headers)

    @task(2)
    def get_engineers(self):
        if self.token:
            self.client.get("/api/engineers", headers=self.headers)

    @task(1)
    def health_check(self):
        self.client.get("/health")

    @task(1)
    def create_alert(self):
        if self.token:
            self.client.post("/api/alerts", headers=self.headers, json={
                "title": f"Load test alert",
                "description": "Generated by locust load test",
                "severity": "MEDIUM",
            })
